id: A3A441424
title: Turning Back the Misfortunes of the Age of Degeneration
type: translation
pechas:
- IC4773E65
- IA654B7B7
- IF6F35CC4
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:11:55.505976
  last_modified_at: 2023-01-04 12:11:55.505984
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IC4773E65/29F9: 10C6
  IA654B7B7/2E62: 10C6
  IF6F35CC4/8D71: 10C6
